name: test
on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.17]
    name: Test with Go version ${{ matrix.go }}
    steps:
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: lint
        run: make lint

      - name: test
        run: make test

      - name: build
        run: make build
