name: test
on:
  push:
    branches:
      - '*'
      - '!renovate/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.17]
    name: Test with Go version ${{ matrix.go }}
    steps:
      - uses: actions/setup-go@v2.2.0
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.0.0

      - name: tools
        run: make tools

      - name: lint
        run: make lint

      - name: test
        run: make test

      - name: build
        run: make build
