name: test
on:
  push:
    branches:
      - '*'
      - '!renovate/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.17]
    name: Test with Go version ${{ matrix.go }}
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: Get dependencies
        run: make install

      - name: lint
        run: make lint

      - name: go test
        run: make test
